apiVersion: v1
kind: Pod
metadata:
  name: dumpster-pod 
  labels: 
    app: exercises
    purpose: k8s-workshop
spec:
  containers:
  - name: dumpster-container
    image: gutek/dumpster:0.1
    ports:
    - containerPort: 80