apiVersion: v1 
kind: Service 
metadata: 
  name: my-svc
spec: 
  type: NodePort 
  selector: 
    app: my-pod
    purpose: k8s-workshop
  ports: 
  - name: http 
    port: 8080 # visble in k8s cluster
    targetPort: 80 # pod's port
    nodePort: 32222 # this port we will use to access app
