apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dumpster-deployment
spec:
  replicas: 4
  selector:
    matchLabels: 
      app: exercises-deployment
      purpose: k8s-workshop
  template:
    metadata:
      labels:
        app: exercises-deployment
        purpose: k8s-workshop
    spec:
      containers:
      - name: dumpster-deployment-container
        image: gutek/dumpster:0.1
        ports:
        - containerPort: 80
        env: 
        - name: DEVCONF 
          value: "2018" 
---
apiVersion: v1 
kind: Service 
metadata: 
  name: dumpster-svc
spec: 
  type: NodePort 
  selector: 
    app: exercises-deployment
    purpose: k8s-workshop
  ports: 
  - name: http 
    port: 8080
    targetPort: 80
    nodePort: 32222

